msg = ones(96,1);
gen = comm.CRCGenerator( ...
    'DirectMethod', true, ...
    'Polynomial',uint8([de2bi(hex2dec('04C11DB7'))]), ...
... %    'InitialConditions', uint8(ones(1,25)), ...
    'ReflectInputBytes', true ...
);
codeword = step(gen,msg);

dec2hex(bi2de(codeword(1:8)'))
dec2hex(bi2de(codeword(9:16)'))
dec2hex(bi2de(codeword(17:24)'))
dec2hex(bi2de(codeword(25:32)'))
