function packet = generatePacket(payload)
    crc = gnuradioCRC32(payload);
    packet = [                          ...
        payload                         ...
        bitand(crc,255)                 ...
        bitand(bitshift(crc,-8),255)    ...
        bitand(bitshift(crc,-16),255)   ...
        bitand(bitshift(crc,-24),255)   ...
    ];
end