% hDataMod = comm.OFDMModulator(...
%     'FFTLength' ,           6,...
%     'NumGuardBandCarriers', [6;5],...
%     'InsertDCNull',         true, ...
%     'PilotInputPort',       true,...
%     'PilotCarrierIndices',  [12;26;40;54],...
%     'CyclicPrefixLength',   16,...
%     'NumSymbols',           12);
% 
% data
% 
% data2ifft = ifft(ifftshift([ zeros(1,leftGuard) data2' zeros(1,rightGuard)]));
% data2out = [data2ifft(end-prefixLen+1:end)'; data2ifft'];

in = dlmread('ofdmsignal.txt',',')';
out = dlmread('ofdmsignal.txt',',');

figure;
stem(imag(in));

figure;
stem(abs(out));
