function packet = generatePayload(payload)
    %vypocet CRC32 podla <32,0x04c11db7,0xffffffff,0xffffffff,true,true>
    %                           generujuci polynom, init, last xor, reflect a este nieco
    crc = gnuradioCRC32(payload);
    packet = [                                ...
        payload                               ...
        uint8(bitand(crc,255))                ...
        uint8(bitand(bitshift(crc,-8),255))   ...
        uint8(bitand(bitshift(crc,-16),255))  ...
        uint8(bitand(bitshift(crc,-24),255))  ...
    ];
end